<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Global Financial Report</title>
    <style>
        body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 12px; color: #333; }
        .header { border-bottom: 1px solid #ddd; padding-bottom: 10px; margin-bottom: 20px; }
        .header h1 { margin: 0; font-size: 20px; color: #111; }
        .header p { margin: 5px 0 0 0; color: #555; }
        .section-title { font-size: 14px; color: #111; border-bottom: 2px solid #10b981; padding-bottom: 3px; margin-top: 30px; margin-bottom: 10px; }
        .stats-grid { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
        .stats-grid td { width: 25%; padding: 10px; border: 1px solid #eee; text-align: center; }
        .stats-grid .stat-value { font-size: 16px; font-weight: bold; color: #1f2937; margin-top: 5px; }
        .stats-grid .stat-label { font-size: 10px; text-transform: uppercase; color: #6b7280; }
        
        table.data-table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
        table.data-table th, table.data-table td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        table.data-table th { background-color: #f9fafb; font-size: 11px; font-weight: bold; text-transform: uppercase; color: #4b5563; }
        table.data-table td { font-size: 12px; color: #374151; }
        .text-right { text-align: right !important; }
        .text-center { text-align: center !important; }
        .text-emerald { color: #059669; font-weight: bold; }
    </style>
</head>
<body>

    <div class="header">
        <h1>Global Financial Report</h1>
        <p><strong>Generated By:</strong> {{ ucfirst($role) }}</p>
        <p><strong>Date:</strong> {{ now()->format('d M Y, H:i') }}</p>
    </div>

    <div class="section-title">Executive Summary</div>
    <table class="stats-grid">
        <tr>
            <td>
                <div class="stat-label">Total Revenue</div>
                <div class="stat-value text-emerald">Rp {{ number_format($data['totalRevenue'] ?? 0, 0, ',', '.') }}</div>
            </td>
            <td>
                <div class="stat-label">Revenue This Month</div>
                <div class="stat-value">Rp {{ number_format($data['revenueThisMonth'] ?? 0, 0, ',', '.') }}</div>
            </td>
            <td>
                <div class="stat-label">MoM Growth</div>
                <div class="stat-value">{{ $data['growthPercent'] ?? 0 }}%</div>
            </td>
            <td>
                <div class="stat-label">Pending Order Value</div>
                <div class="stat-value">Rp {{ number_format($data['pendingOrdersValue'] ?? 0, 0, ',', '.') }}</div>
            </td>
        </tr>
        <tr>
            <td>
                <div class="stat-label">Total Tickets Sold</div>
                <div class="stat-value">{{ number_format($data['totalTicketsSold'] ?? 0) }}</div>
            </td>
            <td>
                <div class="stat-label">Tickets Scanned</div>
                <div class="stat-value">{{ number_format($data['totalTicketsScanned'] ?? 0) }}</div>
            </td>
            <td>
                <div class="stat-label">Completed Orders</div>
                <div class="stat-value">{{ number_format($data['totalOrdersCompleted'] ?? 0) }}</div>
            </td>
            <td>
                <div class="stat-label">Avg Order Value</div>
                <div class="stat-value">Rp {{ number_format($data['avgOrderValue'] ?? 0, 0, ',', '.') }}</div>
            </td>
        </tr>
    </table>

    @if(isset($data['revenueByCategory']) && count($data['revenueByCategory']) > 0)
    <div class="section-title">Revenue By Category</div>
    <table class="data-table">
        <thead>
            <tr>
                <th>Category</th>
                <th class="text-right">Revenue (Rp)</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($data['revenueByCategory'] as $cat)
                <tr>
                    <td>{{ $cat['name'] }}</td>
                    <td class="text-right text-emerald">{{ number_format($cat['revenue'], 0, ',', '.') }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>
    @endif

    @if(isset($data['ticketTypeBreakdown']) && count($data['ticketTypeBreakdown']) > 0)
    <div class="section-title">Ticket Type Breakdown</div>
    <table class="data-table">
        <thead>
            <tr>
                <th>Ticket Type</th>
                <th class="text-center">Total Sold</th>
                <th class="text-right">Total Revenue (Rp)</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($data['ticketTypeBreakdown'] as $tt)
                <tr>
                    <td>{{ $tt->name }}</td>
                    <td class="text-center">{{ number_format($tt->total_sold) }}</td>
                    <td class="text-right text-emerald">{{ number_format($tt->total_revenue, 0, ',', '.') }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>
    @endif

    @if(isset($data['topEvents']) && count($data['topEvents']) > 0)
    <div class="section-title">Top Profitable Events</div>
    <table class="data-table">
        <thead>
            <tr>
                <th>#</th>
                <th>Event Title</th>
                <th>Status</th>
                <th class="text-center">Completed Orders</th>
                <th class="text-right">Total Revenue (Rp)</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($data['topEvents'] as $index => $event)
                <tr>
                    <td>{{ $index + 1 }}</td>
                    <td>{{ $event['title'] }}</td>
                    <td>{{ ucfirst($event['status']) }}</td>
                    <td class="text-center">{{ number_format($event['completed_orders']) }}</td>
                    <td class="text-right text-emerald">{{ number_format($event['total_revenue'], 0, ',', '.') }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>
    @endif

    <p style="margin-top: 40px; font-size: 10px; color: #9ca3af; text-align: center;">Generated by Tixxy</p>

</body>
</html>
